name: ag
favicon: null
layout_spectrum: 0.1395539145451039
typography_spectrum: 0.9876859707292169
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#006d3b'
    - '#91c57b'
    - '#2b2a29'
    - '#757574'
  brandStrength: 0.875
  lightness: 0.8053608909249306
  saturation: 0.5318318898789585
  rhythmicContrast: 0.35110620548948646
purpose: []
