name: ag
favicon: null
layout_spectrum: 0.1395539145451039
typography_spectrum: 0.9876859707292169
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.7492310858797282
  lightness: 0.8053608909249306
  saturation: 0.5318318898789585
  rhythmicContrast: 0.35110620548948646
purpose: []
